import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/app/components/header/header'
import Footer from "@/app/components/header/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className + ' h-screen w-screen overflow-x-hidden'}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
